# MCU name
MCU = RP2040

# split
SERIAL_DRIVER = vendor
SPLIT_KEYBOARD = yes
SPLIT_TRANSACTION_ENABLE = yes

# ENCODER
ENCODER_ENABLE = yes

# POINTING DEVICE
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
MOUSEKEY_ENABLE = yes
SPLIT_POINTING_ENABLE = yes
SPI_DRIVER_REQUIRED = yes

# VIA
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

# LED
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no

# DEBUG
CONSOLE_ENABLE = yes

SRC += lib_trackball.c
SRC += lib_led.c