#pragma once

#define EE_HANDS
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

// Split parameter
#define SPLIT_HAND_PIN GP3
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP12
#define SERIAL_USART_RX_PIN GP13
#define SPLIT_USB_TIMEOUT 2000
#define SPLIT_USB_TIMEOUT_POLL 20


// SPI Setting
#define SPI_DRIVER SPID0
#define POINTING_DEVICE_CS_PIN GP5
#define SPI_SCK_PIN GP6
#define SPI_MISO_PIN GP4
#define SPI_MOSI_PIN GP7


// PMW3360 Setting
#define POINTING_DEVICE_INVERT_X_RIGHT
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define POINTING_DEVICE_SCROLL_ENABLE


// Encoder Setting
#define ENCODER_A_PINS { GP8 }
#define ENCODER_B_PINS { GP9 }
#define ENCODER_RESOLUTION 4


// LED Setting
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_MAX_LAYERS 4
#define LED_LAYOUT(LED0){LED0}
#define RGBLIGHT_LED_MAP LED_LAYOUT(0)


// Vial Setting
#define VIAL_KEYBOARD_UID {0x38, 0x51, 0xC5, 0xF8, 0xE6, 0x22, 0xC0, 0x99}
#define VIAL_UNLOCK_COMBO_ROWS {0, 1}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}